### ISSUE TITLE
Promote User to Artist

### ISSUE THREAD

**Issue by AntonioMrtz** [AntonioMrtz/SpotifyElectron#129]
Create an endpoint for PATCH /users/:id/promote that accepts the name of an existing user and:

* Deletes the user from user database ( method already created on user_service )
* Creates an artist with the previous user data ( method already created on user_service )
* Add tests that cover whole functionality

---
__🖐️ Learn [how to CONTRIBUTE](https://antoniomrtz.github.io/SpotifyElectron_Web/docs/CONTRIBUTING/), all help is welcomed :)__

__📚 Check out the [project documentation](https://antoniomrtz.github.io/SpotifyElectron_Web/docs/) for more info__

__⭐ Help this project grow by giving it a star if you like it!__

__😵 Trello links are used for traceability, do not ask to join the board before leaving a comment in the related issue__

**Comment by AntonioMrtz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Endpoint promote user to artist](https://trello.com/c/t2enbTcO/321-endpoint-promote-user-to-artist)

**Comment by xiomaraR** [comment]
Thanks for suggesting this issue! I’d like to work on it.

**Comment by AntonioMrtz** [comment]
@xiomaraR All yours, just tell me if you need anything :)

**Comment by AntonioMrtz** [comment]
Hi @xiomaraR , how is it going? This weekend I made some major changes related to JWT Authentication. One of the last tasks I had pending about developer experience on the app was to re-enable Swagger docs for backend. Because of the JWT Middleware we had before request had to be made using frontend or Postman, the authentication field all protected endpoints had didn't work as expected. I think I will create a new docs page about tips/help on how to develop the app such as debugging, use of swagger etc.

But for now you can use Swagger docs for making backend requests, Im sure it will improve developer experience and ease the testing/develop. For using Swagger requests on protected endpoints you will need:

* Go to localhost:8000/docs with backend launched
* Create a user
* Use login endpoint putting only user and password. It will return the user associated JWT Token.
* Click on authorize green button on top right corner and introduce the previously generated JWT Token.
* Make any request and it should work

Let me know if its useful or if you have any questions about the task. 😃

**Comment by xiomaraR** [comment]
Hey @AntonioMrtz so I couldn't find a method in user_service or anywhere else that creates artist from user, so I tried to create one. Will you let me know if I'm on the right track? I wasn't sure of the best way to fetch the user data
```
def upgrade_user_to_artist(user_name: str) -> None:
    """Promote a user to an artist then deletes user

    Args:
        user_name (str): user name

    Raises:
        UserServiceException: unexpected error upgrading user
    """
    try:

        user = user_repository.get_user(user_name)
        if artist_service.create_artist(user.name, user.photo, user.password):
            base_user_service.delete_user(user_name)
    except Exception as exception:
        user_service_logger.exception(
            f"Unexpected error upgrading {user_name} to artist"
        )
        raise UserServiceException from exception

**Comment by AntonioMrtz** [comment]
Hi @xiomaraR. Yeah, theres no `create artist from user` method, the goal was to create the structure for it in this issue. The code looks good but theres a few things you can improve:

* `if artist_service.create_artist(user.name, user.photo, user.password):` doesnt return. If something went wrong an exception will be thrown. So theres no need for an if statement there
* Check for every exception that can be thrown in the repository layer. Its not necessary but having `(RepositoryException,Exception)` can lead to better readability
* We want to make all needed checks before making certain transactions with the database. Example: `validate_user_exists` is needed before getting the user from db. If we add this check we will need to handle `UserNotFoundException` exception and raise it into controller layer so we can send a 404 response.
* This code is a serious candidate for a transaction schema. We will tackle this in another task but for now leave a comment saying `# TODO make it a transaction` inside `upgrade_user_to_artist`.

Let me know if you need anything. I will be happy to answer 😀

**Comment by AntonioMrtz** [comment]
Hi @xiomaraR are u still working on this issue? :)

**Comment by berkaykrc** [comment]
Can I take over this issue?

**Comment by AntonioMrtz** [comment]
Hi @berkaykrc , all yours :). As always let me know if you have any questions

**Comment by berkaykrc** [comment]
Thank you again! I wrote the endpoint with tests, but other tests are failing. I do not know if it's my problem or not. Furthermore, I will check out it at weekend. I couldn't get create user at swagger also. Getting HTTP 500 with BaseUser already exist but cannot login.

**Comment by AntonioMrtz** [comment]
Hi,
I tried it myself and encountered the same error in production. The issue may be related to a recently merged PR that refactored the user system. I'll check it ASAP. Thanks for noticing!

**Comment by AntonioMrtz** [comment]
hi @berkaykrc . I notice some problems with ENV=TEST for development. Using TEST mode enables an in-memory MongoDB database. The issue with that database is that we have 2 workers (threads that serve the app) meaning each one has its own instance of the DB. This only happens in TEST as the in-memory database is only for testing environments :). 

I will drop a patch ASAP :). Thanks a lot for reporting the problem

**Comment by berkaykrc** [comment]
> Hi, If you're not getting any database connection error the app is using the test in-memory database. I could not reproduce the BaseUser error you're getting on production (tag v2.02).
> 
> What parts of the app fail with tests? Did you get the newest version of master branch?

Hey,@AntonioMrtz hope you doing fine! I do not get any database connection error and the app using ENV_VALUE=DEV since I tried to create a user just to test if my code actually works for promote User in this case it will be me to Artist. 
```bash
python -m app
2025-02-02 01:15:16,846 -  PROPERTIES_MANAGER - INFO - Initializing PropertiesManager
2025-02-02 01:15:16,848 -  PROPERTIES_MANAGER - INFO - Environment variables loaded: ['MONGO_URI', 'SECRET_KEY_SIGN', 'SERVERLESS_FUNCTION_URL', 'ENV_VALUE']
2025-02-02 01:15:16,848 -  PROPERTIES_MANAGER - INFO - Architecture selected: BLOB
INFO:     Will watch for changes in these directories: ['/home/berkay/SpotifyElectron/Backend']
WARNING:  "workers" flag is ignored when reloading is enabled.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [44026] using StatReload
2025-02-02 01:15:18,084 -  PROPERTIES_MANAGER - INFO - Initializing PropertiesManager
2025-02-02 01:15:18,085 -  PROPERTIES_MANAGER - INFO - Environment variables loaded: ['MONGO_URI', 'SECRET_KEY_SIGN', 'SERVERLESS_FUNCTION_URL', 'ENV_VALUE']
2025-02-02 01:15:18,085 -  PROPERTIES_MANAGER - INFO - Architecture selected: BLOB
INFO:     Started server process [44046]
INFO:     Waiting for application startup.
2025-02-02 01:15:18,234 -  MAIN - INFO - Spotify Electron Backend Started
2025-02-02 01:15:18,295 -  SONG_SERVICE_PROVIDER - INFO - Song service MODULE selected: BLOB
INFO:     Application startup complete.
INFO:     127.0.0.1:47414 - "GET /docs HTTP/1.1" 200 OK
email-validator not installed, email fields will be treated as str.
To install, run: pip install email-validator
INFO:     127.0.0.1:47414 - "GET /openapi.json HTTP/1.1" 200 OK
2025-02-02 01:16:35,648 -  JWT_BEARER_AUTH - WARNING - Request with no cookies <starlette.requests.Request object at 0x7f84fdd422d0>, getting JWT from Authentication Header
INFO:     127.0.0.1:48398 - "GET /users/whoami HTTP/1.1" 403 Forbidden
2025-02-02 01:17:06,427 -  USER_SERVICE - ERROR - Unexpected error in User Service creating user: berkay
Traceback (most recent call last):
  File "/home/berkay/SpotifyElectron/Backend/app/spotify_electron/user/user/user_service.py", line 99, in create_user
    base_user_service_validations.validate_user_should_not_exist(user_name)
  File "/home/berkay/SpotifyElectron/Backend/app/spotify_electron/user/validations/base_user_service_validations.py", line 63, in validate_user_should_not_exist
    raise BaseUserAlreadyExistsException
app.spotify_electron.user.base_user_schema.BaseUserAlreadyExistsException: BaseUser already exists
INFO:     127.0.0.1:42558 - "POST /users/?name=berkay&photo=https%3A%2F%2Fphoto&password=123456789 HTTP/1.1" 500 Internal Server Error
                                                                                                                   
INFO:     127.0.0.1:42558 - "POST /users/?name=berkay&photo=https%3A%2F%2Fphoto&password=123456789 HTTP/1.1" 500 Internal Server Error
```
I also checked MongoDB SpotifyElectron document to see if it's actually created user but the document only has populated users starting with "item-" prefix. 

I have the newest version of master branch. In /docs/ endpoint it says Spotify Electron Backend API 2.0.2 OAS 3.1 I suppose it equivalent to v2.02 tag version?

These are the tests failing due BaseUser problem I mentioned.

FAILED tests/test__artist.py::test_get_artist_correct - assert 500 == 202
FAILED tests/test__artist.py::test_get_artist_not_found - assert 500 == 404
FAILED tests/test__artist.py::test_post_artist_correct - assert 500 == 201
FAILED tests/test__artist.py::test_delete_artist_correct - assert 500 == 201
FAILED tests/test__artist.py::test_delete_artist_not_found - assert 500 == 404
FAILED tests/test__artist.py::test_get_artists_correct - assert 500 == 201
FAILED tests/test__artist.py::test_get_total_streams_artist_correct - assert 500 == 201
FAILED tests/test__artist.py::test_get_artist_songs_correct - assert 500 == 201
FAILED tests/test__artist.py::test_get_artist_songs_user_unauthorized - assert 500 == 201
FAILED tests/test__base_users.py::test_patch_playback_history_user_correct - assert 500 == 202
FAILED tests/test__base_users.py::test_patch_playback_history_artist_correct - assert 500 == 201
FAILED tests/test__base_users.py::test_patch_playback_history_invalid_bad_user - assert 500 == 201
FAILED tests/test__base_users.py::test_patch_playback_history_user_correct_insert_6_songs - assert 500 == 201
FAILED tests/test__base_users.py::test_patch_saved_playlist_user_correct - assert 500 == 201
FAILED tests/test__base_users.py::test_patch_saved_playlist_artist_correct - assert 500 == 201
FAILED tests/test__base_users.py::test_delete_saved_playlist_artist_correct - assert 500 == 201
FAILED tests/test__base_users.py::test_delete_saved_playlist_user_invalid - assert 500 == 201
FAILED tests/test__base_users.py::test_delete_saved_playlist_user_correct - assert 500 == 201
FAILED tests/test__base_users.py::test_whoami_artist - assert 500 == 201
FAILED tests/test__base_users.py::test_whoami_user - assert 500 == 201
FAILED tests/test__base_users.py::test_add_playlist_to_owner_user_correct - assert 500 == 201
FAILED tests/test__base_users.py::test_add_playlist_to_owner_artist_correct - assert 500 == 201
FAILED tests/test__base_users.py::test_delete_playlist_from_owner_user_correct - assert 500 == 201
FAILED tests/test__base_users.py::test_delete_playlist_from_owner_artist_correct - assert 500 == 201
FAILED tests/test__base_users.py::test_get_user_relevant_playlist_correct - assert 500 == 202
FAILED tests/test__base_users.py::test_get_artist_relevant_playlist_correct - assert 500 == 201
FAILED tests/test__base_users.py::test_get_user_relevant_playlist_user_not_found - assert 500 == 201
FAILED tests/test__base_users.py::test_get_user_playlist_names_correct - assert 500 == 201
FAILED tests/test__base_users.py::test_get_artist_playlist_names_correct - assert 500 == 201
FAILED tests/test__base_users.py::test_get_user_playlist_names_user_not_found - assert 500 == 201
FAILED tests/test__base_users.py::test_get_user_playlists_correct - assert 500 == 201
FAILED tests/test__base_users.py::test_get_artist_playlists_correct - assert 500 == 201
FAILED tests/test__base_users.py::test_get_user_playlists_user_not_found - assert 500 == 201
FAILED tests/test__base_users.py::test_get_user_playback_history_correct - assert 500 == 201
FAILED tests/test__base_users.py::test_get_user_playback_history_user_not_found - assert 500 == 201
FAILED tests/test__base_users.py::test_promote_user_to_artist - assert 422 == 204
FAILED tests/test__genre.py::test_get_genres_correct - assert 500 == 202
FAILED tests/test__login.py::test_login_artist - assert 500 == 202
FAILED tests/test__login.py::test_login_user - assert 500 == 202
FAILED tests/test__login.py::test_login_user_not_found - assert 200 == 404
FAILED tests/test__login.py::test_login_user_bad_password - assert 500 == 201
FAILED tests/test__login.py::test_login_user_with_jwt - assert 500 == 201
FAILED tests/test__login.py::test_login_user_with_jwt_user_not_found - assert 500 == 201
FAILED tests/test__playlist.py::test_get_playlist_correct - assert 500 == 202
FAILED tests/test__playlist.py::test_get_playlist_not_found - assert 500 == 201
FAILED tests/test__playlist.py::test_post_playlist_correct - assert 500 == 201
FAILED tests/test__playlist.py::test_delete_playlist_correct - assert 500 == 201
FAILED tests/test__playlist.py::test_update_playlist_correct - assert 500 == 201
FAILED tests/test__playlist.py::test_get_playlists - assert 500 == 201
FAILED tests/test__playlist.py::test_add_songs_to_playlist_correct - assert 500 == 202
FAILED tests/test__playlist.py::test_add_songs_to_playlist_playlist_not_found - assert 500 == 201
FAILED tests/test__playlist.py::test_add_songs_to_playlist_song_not_found - assert 500 == 201
FAILED tests/test__playlist.py::test_remove_song_from_playlist_correct - assert 500 == 201
FAILED tests/test__playlist.py::test_remove_song_from_playlist_playlist_not_found - assert 500 == 201
FAILED tests/test__playlist.py::test_remove_song_from_playlist_song_not_found - assert 500 == 201
FAILED tests/test__search.py::test_get_search_by_name_correct - assert 500 == 202
FAILED tests/test__search.py::test_get_search_by_name_invalid_name - assert 500 == 201
FAILED tests/test__song.py::test_post_cancion_correct - assert 500 == 202
FAILED tests/test__song.py::test_post_cancion_user_as_artist - assert 500 == 201
FAILED tests/test__song.py::test_post_cancion_correct_check_valid_duration - assert 500 == 201
FAILED tests/test__song.py::test_post_cancion_correct_check_invalid_duration - assert 500 == 201
FAILED tests/test__song.py::test_post_cancion_correct_check_song_already_exists - assert 500 == 201
FAILED tests/test__song.py::test_get_cancion_correct - assert 500 == 201
FAILED tests/test__song.py::test_get_cancion_invalid_name - assert 500 == 201
FAILED tests/test__song.py::test_delete_cancion_correct - assert 500 == 201
FAILED tests/test__song.py::test_patch_number_plays_cancion_correct - assert 500 == 201
FAILED tests/test__song.py::test_patch_number_of_plays_song_not_found - assert 500 == 201
FAILED tests/test__song.py::test_patch_song_invalid_name - assert 500 == 201
FAILED tests/test__song.py::test_post_song_uploaded_songs_updated - assert 500 == 201
FAILED tests/test__song.py::test_post_song_uploaded_songs_bad_artist - assert 500 == 201
FAILED tests/test__song.py::test_delete_song_uploaded_songs_updated - assert 500 == 201
FAILED tests/test__song.py::test_get_cancion_by_genre - assert 500 == 201
FAILED tests/test__song.py::test_get_cancion_by_genre_bad_genre - assert 500 == 201
FAILED tests/test__stream.py::test_stream_controller_song_invalid_range_no_range_header - assert 500 == 202
FAILED tests/test__stream.py::test_stream_controller_song_invalid_range_greater_than_file_size - assert 500 == 201
FAILED tests/test__stream.py::test_stream_controller_song_invalid_range_start_smaller_end_bytes - assert 500 == 201
FAILED tests/test__stream.py::test_stream_controller_song_not_found - assert 500 == 202
FAILED tests/test__stream.py::test_stream_controller_song_range_correct - assert 500 == 201
FAILED tests/test__user.py::test_get_user_correct - assert 500 == 202
FAILED tests/test__user.py::test_get_user_not_found - assert 500 == 404
FAILED tests/test__user.py::test_post_user_correct - assert 500 == 201
FAILED tests/test__user.py::test_delete_user_correct - assert 500 == 201
FAILED tests/test__user.py::test_delete_user_not_found - assert 500 == 404
FAILED tests/test__user.py::test_check_encrypted_password_correct - app.spotify_electron.user.user.user_schema.UserServiceException: Error accessing User Service
FAILED tests/test__user.py::test_check_encrypted_password_different - app.spotify_electron.user.user.user_schema.UserServiceException: Error accessing User Service
========================================================== 85 failed, 45 passed, 1 skipped, 5 warnings in 18.36s ===========================================================

**Comment by berkaykrc** [comment]
> hi [@berkaykrc](https://github.com/berkaykrc) . I notice some problems with ENV=TEST for development. Using TEST mode enables an in-memory MongoDB database. The issue with that database is that we have 2 workers (threads that serve the app) meaning each one has its own instance of the DB. This only happens in TEST as the in-memory database is only for testing environments :).
> 
> I will drop a patch ASAP :). Thanks a lot for reporting the problem

Thank you too! Glad I could help you find out about this.

**Comment by AntonioMrtz** [comment]
Hi @berkaykrc. I tried to reproduce it with:

Latest commit `bb1b16f`

with environment

```
MONGO_URI=mongodb://root:root@127.0.0.1:27017/
ENV_VALUE=DEV
ARCH=BLOB
```

## User creation

```
2025-02-02 16:58:09,101 -  PROPERTIES_MANAGER - INFO - Initializing PropertiesManager
2025-02-02 16:58:09,102 -  PROPERTIES_MANAGER - INFO - Environment variables loaded: ['MONGO_URI', 'SECRET_KEY_SIGN', 'SERVERLESS_FUNCTION_URL', 'ENV_VALUE']
2025-02-02 16:58:09,102 -  PROPERTIES_MANAGER - INFO - Architecture selected: BLOB
INFO:     Will watch for changes in these directories: ['/home/antonio-ubuntu/Desktop/VSCODE_WORKSPACE/SpotifyElectron/Backend']
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [77753] using StatReload
2025-02-02 16:58:09,691 -  PROPERTIES_MANAGER - INFO - Initializing PropertiesManager
2025-02-02 16:58:09,692 -  PROPERTIES_MANAGER - INFO - Environment variables loaded: ['MONGO_URI', 'SECRET_KEY_SIGN', 'SERVERLESS_FUNCTION_URL', 'ENV_VALUE']
2025-02-02 16:58:09,692 -  PROPERTIES_MANAGER - INFO - Architecture selected: BLOB
INFO:     Started server process [77757]
INFO:     Waiting for application startup.
2025-02-02 16:58:09,839 -  MAIN - INFO - Spotify Electron Backend Started
2025-02-02 16:58:09,857 -  SONG_SERVICE_PROVIDER - INFO - Song service MODULE selected: BLOB
INFO:     Application startup complete.

----> Insert user

2025-02-02 16:59:50,863 -  USER_REPOSITORY - INFO - User added to repository: {'name': 'test', 'photo': '', 'register_date': '2025-02-02T16:59:50', 'password': b'$2b$12$nP7MQ8h2xo1TgoGirt.5FOOhKxiQ1KCeMawcogjFXpYMNp.D1K4Yu', 'saved_playlists': [], 'playlists': [], 'playback_history': [], '_id': ObjectId('679f9676d981af9d5ef4739c')}
2025-02-02 16:59:50,863 -  USER_SERVICE - INFO - User test created successfully
INFO:     127.0.0.1:42998 - "POST /users/?name=test&photo=test&password=test HTTP/1.1" 201 Created


----> Insert same user

2025-02-02 16:59:54,441 -  USER_SERVICE - ERROR - User already exists: test
Traceback (most recent call last):
  File "/home/antonio-ubuntu/Desktop/VSCODE_WORKSPACE/SpotifyElectron/Backend/app/spotify_electron/user/user/user_service.py", line 100, in create_user
    base_user_service_validations.validate_user_should_not_exist(user_name)
  File "/home/antonio-ubuntu/Desktop/VSCODE_WORKSPACE/SpotifyElectron/Backend/app/spotify_electron/user/validations/base_user_service_validations.py", line 63, in validate_user_should_not_exist
    raise BaseUserAlreadyExistsError
app.spotify_electron.user.base_user_schema.BaseUserAlreadyExistsError: User already exists
INFO:     127.0.0.1:42998 - "POST /users/?name=test&photo=test&password=test HTTP/1.1" 400 Bad Request
```

----> Login user

```
2025-02-02 17:01:49,062 -  BASE_USER_SERVICE - INFO - Password obtained for User: test
2025-02-02 17:01:49,397 -  AUTH_SERVICE - INFO - JWT created from data: {'access_token': 'test', 'role': 'user', 'token_type': 'bearer'}
2025-02-02 17:01:49,397 -  AUTH_SERVICE - INFO - User test logged successfully
INFO:     127.0.0.1:49998 - "POST /login/ HTTP/1.1" 200 OK
```

## Tests

```
(venv) antonio-ubuntu@antonio-ubuntu:~/Desktop/VSCODE_WORKSPACE/SpotifyElectron/Backend$ python -m pytest tests/
==================== test session starts =====================
platform linux -- Python 3.12.3, pytest-8.0.1, pluggy-1.5.0
rootdir: /home/antonio-ubuntu/Desktop/VSCODE_WORKSPACE/SpotifyElectron/Backend/tests
configfile: pytest.ini
plugins: cov-4.1.0, env-1.1.3, anyio-4.8.0, mock-3.12.0
collected 116 items                                          

tests/test__artist.py ...........                      [  9%]
tests/test__base_users.py ............................ [ 33%]
........                                               [ 40%]
tests/test__genre.py ...                               [ 43%]
tests/test__health.py .                                [ 43%]
tests/test__login.py .......                           [ 50%]
tests/test__playlist.py .......s.......                [ 62%]
tests/test__properties_manager.py ........             [ 69%]
tests/test__search.py ..                               [ 71%]
tests/test__song.py .................                  [ 86%]
tests/test__stream.py .....                            [ 90%]
tests/test__user.py ...........                        [100%]

== 115 passed, 1 skipped, 330 warnings in 68.48s (0:01:08) ===
```

**Comment by berkaykrc** [comment]
Thanks for the fast patch @AntonioMrtz. I was able to create a new test user in the database. For some reason, both previous users I created were in the database and the new one, but I cannot find them in the mongo-express administration dashboard under SpotifyElectron database users collection. They only show up when I filter from the top of the page. Only two pages are visible on the dashboard could be the reason they are not visible while I can see the number of documents increasing and can query with their names in API.

I still need to read your latest commit to see what changes you made. The exceptions catch my eye in first sight and I got some warning about them, so I need to refactor my code to match them.
